Libraries/StyleSheet/extendProperties.web.js

transform:[{ scale: 0.5 }] was not working
there were a common code to process the style value AND the transform value. This PR split the CSS properties from the transform functions.

Fixes transform value (like scale, scaleX,..) that are in [0,1] range to not be set to 1

---

Libraries/ActivityIndicator/ActivityIndicator.web.js
Libraries/Animated/AnimatedImplementation.js
Libraries/DrawerLayout/DrawerLayout.web.js
Libraries/Image/Image.web.js
Libraries/ProgressView/ProgressView.web.js
Libraries/SegmentedControl/SegmentedControl.web.js
Libraries/Switch/Switch.web.js
Libraries/Text/Text.web.js
Libraries/Touchable/TouchableHighlight.web.js
Libraries/Touchable/TouchableOpacity.web.js
Libraries/Utilties/NativeMethodsMixin.web.js
Libraries/Utilties/UIManager.web.js
Libraries/View/View.web.js
Libraries/ViewPager/ViewPager.web.js

fixes #41
now we can use `ref.setNativeProps()` as well as `ref.measure(cb)` and `measureLayout` on some native components like View and Text.
UIManager is also exposed (like in RN) and you can progressively add all the remaining methods as you need them.

Fixes #41: add UIManager and NativeMethodsMixin

---

package.json

this avoids problem when running `react-native start` when also depending on fbjs at the root (it's required for depending on react and dedup of npm deps)

depends on fbjs ^0.6.1

---

package.json

users may have a different version of babel installed globally, or none at all (which is what is recommended by the Babel project).  safer to use the local babel.

don't assume babel is installed globally

---

Libraries/TextInput/TextInput.web.js

I want to receive keyPress events to detect if the user pressed enter in the text field.  this patch exposes the standard React key events on TextInput.

expose onKeyUp, onKeyDown and onKeyPress in TextInput

---

Libraries/ViewPager/ViewPager.web.js

To avoid [this](http://stackoverflow.com/questions/29995488/react-styles-prop-returns-object-object-for-an-array) issue, let's have styles as object instead array.

Make ViewPager children styles as object

---

package.json
webpack.config.js

We must import babel-polypill lib, if we want to use
async/await on Babel 6, otherwise it will cause ‘regeneratorRuntime is
not defined’ error.

add babel-polyfill support

---

Libraries/ScrollView/ScrollView.web.js
Libraries/StyleSheet/setDefaultStyle.web.js

> 问题一：ScrollView 中 contentContainer 的样式`position: absolute`，导致ScrollView中内容不占位。
> 问题二：根节点flex box 导致子节点被压缩。与客户端显示不一致
附图：
问题一：
问题二：

ScrollView 和 根节点样式 导致 与客户端显示不一致

---

Libraries/ScrollView/ScrollView.web.js
Libraries/StyleSheet/setDefaultStyle.web.js
README-zh.md
README.md

昨天提交了ScrollView的一些展示不一致的问题，后来使用又发现了一些问题，例如：
1. 如果去掉position: absolute 会让垂直的scrollview显示又会被flex box压缩，所以还是不能去掉。因此还是得手动设置scrollview的高度，不能被子元素撑起来，在文档中标出。
2. 因为内部设置成了position: absolute，因此padding在scrollview中不会生效，所以把它挪到内层。
3. 根节点样式去掉Flex之后第一个不会占满，因此设置一个view的高度100%。
现在已经没问题了

ScrollView 和 Rootstyle 与客户端显示不一致，修复

---

scripts/publish.js

For example, during the babel transform.

Do not hide errors occuring during publish.js.

---

Libraries/ActivityIndicator/ActivityIndicator.web.js
Libraries/DrawerLayout/DrawerLayout.web.js
Libraries/Image/Image.web.js
Libraries/ListView/ListView.web.js
Libraries/ProgressView/ProgressView.web.js
Libraries/ScrollView/ScrollView.web.js
Libraries/SegmentedControl/SegmentedControl.web.js
Libraries/Switch/Switch.web.js
Libraries/Touchable/TouchableBounce.web.js
Libraries/Touchable/TouchableHighlight.web.js
Libraries/Touchable/TouchableOpacity.web.js
Libraries/Touchable/TouchableWithoutFeedback.web.js
Libraries/ViewPager/ViewPager.web.js

Otherwise, the getInitialState etc. helpers for the mixin class
will not be applied.

For ES6 classes, we need to use mixin.onClass.

---

Libraries/react-web.js
scripts/rewrite-modules.js

Recently, the "publish.js" script was added. The intention behind it, as far as I can tell, is that the built version no longer needs the user to define the "haste" webpack plugin, since all the files are rewritten to reference each other using the regular resolve system.
This doesn't work for me, for a couple of reasons:
1) The ``rewrite_modules`` babel plugin does not handle ES6 imports. I have merged in the changes from the most recent version from ``fbjs``, where imports are supported.
2) At the root level, in ``react-web.js``, the paths being generated are "StyleSheet/StyleSheet.web", but for node's require import to work, they need to be "./StyleSheet/StyleSheet.web".
3) In b903e7ffed387f165e90088002f0249bcd5d852b, the exports in ``react-web.js`` were rewritten to ES6. The problem …

Build/Importing/Exporting seems currently broken.

---

Libraries/Utilties/NativeMethodsMixin.web.js
Libraries/Utilties/setNativeProps.web.js

Now expects the third "component" argument to be passed.
W/o this an error would be raised:
Cannot read property '_debugID' of undefined
See also: Cannot read property '_debugID' of undefined

React 1.5 CSSPropertyOperations signature fix.

---

Libraries/Touchable/TouchableHighlight.web.js
Libraries/Touchable/TouchableOpacity.web.js
Libraries/Touchable/TouchableWithoutFeedback.web.js

修复点击组件在页面滚动时误触onPress事件，修复issue[#82](https://github.com/taobaofed/react-web/issues/82)

修复点击组件在页面滚动时误触onPress事件

---

Libraries/Touchable/TouchableHighlight.web.js
Libraries/Touchable/TouchableOpacity.web.js
Libraries/Touchable/TouchableWithoutFeedback.web.js

ios平台中浏览器event.touchHistory对象的长度与安卓平台不一致，导致ios平台下点击出错

修复ios平台浏览器中touchHistory长度与安装平台不一致引起的不兼容问题

---

.npmignore
Libraries/Image/Image.web.js
Libraries/LayoutAnimation/LayoutAnimation.web.js
Libraries/LayoutAnimation/Layoutanimation.h5.js
Libraries/RefreshControl/RefreshControl.web.js
Libraries/Touchable/TouchableHighlight.web.js
Libraries/Touchable/TouchableOpacity.web.js
Libraries/Touchable/TouchableWithoutFeedback.web.js
Libraries/react-web.js
README-zh.md
README.md
local-cli/generator-web/templates/webpack.config.js
package.json

实际使用 react-web 经常会需要修改 react-web 本身，而经过 babel 转换过的代码修改起来太累。在看到 react-native 和一些 react-native 第三方库比如 react-native-scrollable-tab-view 都直接在 node_modules/ 中呈现未经 babel 转换的代码后，以及为了能直接让 react-web start 使用那些 react-native 第三方库，所以我做了这些修改，主要是通过 webpack.config.js 中的 exclude: /(node_modules\/(?!react))/ 让 babel 在编译/运行 APP 的过程中去处理 node_modules/react*，如果你们接受这个 pull request 的话，我觉得你们只需要将 npm install --save git+https://github.com/flyskywhy/react-web.git 这句修改成你们的 github 地址合并到 react-web init 的脚本中，并修改 README.md 中相应的地方。
另外还修改了Touchable 组件的 BUG ，以及添加了 LayoutAnimation 和 RefreshControl 这两个组件，在 Image 组件中添加了 getSize()。
还有就是在 webpack.config.js 中使用了 cheap-module-eval-source-map ，这样调试 BUG 时就能很容易定位到精确的源代码文件而不是找不到北的 bundle.js
在经过这些修改后， https://github.com/flyskywhy/noder-react-native 就能正常运行 web 版了
附： 我看到 携程 的 react-web …

直接使用 Libraries/ 而非 babel 转换过的 lib/

---

README.md
react-web-cli/index.js

fix `react-web init --version <alternative react-web package>`, ref to react-native-cli

fix `react-web init --version <alternative react-web package> <ExistedProjectDir>`

---

local-cli/generator-web/templates/webpack.config.js

As I checked bundle.js again and again, webpack will bundle the first matched from left to right order in resolve.extensions['.web.js', '.ios.js', '.android.js'], so this PR will resolve .web.js issue #95 and #143 and stlll meet the demand of .ios.js and .android.js in PR #93

Add .web.js support

---

Libraries/Platform/Platform.web.js

https://facebook.github.io/react-native/docs/platform-specific-code.html
There is also a Platform.select method available, that given an object containing Platform.OS as keys, returns the value for the platform you are currently running on.

adds support for ...Platform.select (React 15)

---

Libraries/Dimensions/Dimensions.web.js

Is it returning cached props on purpose? I noticed this comment in the code: 
```js
// Not map to real window size, because that map to screen size in native env.
```

return live dimensions (vs cached)

---

Libraries/Touchable/TouchableHighlight.web.js
Libraries/Touchable/TouchableOpacity.web.js

looks like i didn't finish the job in #90 
problem: any styles passed in to TouchableHighlight/Opacity override defaultProps.style, and result in a select (not pointer) cursor

ensure default to cursor pointer for TouchableHighlight / TouchableOpacity

---

local-cli/generator-web/index.js
local-cli/generator-web/templates/webpack.config.js
react-web-cli/index.js

`react-web init`:
This PR fixed ENOENT on Windows that described in #131 
`react-web start`:
This PR fixed an error on Windows, and the remaining `react-web start` error on Windows described in #173 need another PR https://github.com/yuanyan/haste-resolver/pull/2

Windows development support

---

Libraries/StyleSheet/extendProperties.web.js

setting the default values for the flex shorthand: https://developer.mozilla.org/en-US/docs/Web/CSS/flex
(not sure if you want to specifically do browser detection for IE)

flex fix for IE11

---

local-cli/generator-web/index.js

Fix `react-web init` on Windows `Error: Cannot find module 'D:\proj\RN\node_modules\npm\bin\npm-cli.js'`
也请再发个新版到 https://www.npmjs.com/package/react-web 上，以便 `react-web init RN` 这样的命令能在 Windows 下正常执行，谢谢

Fix `react-web init` on Windows Error again

---

Libraries/StatusBar/StatusBar.web.js
local-cli/generator-web/templates/webpack.config.js

1. Fix <StatusBar /> will cause `Uncaught Invariant Violation: Element type is invalid`, so that no need 
```
{Platform.OS !== 'web' && (
<StatusBar
......
/>
)}
```
on exist react-native project.
2. Avoid source map debugging to useless file `?d41d` by not babel node_modules/react/ in `webpack.config.js`
as you can see, before:
after:

Avoid source map debugging to useless file `?d41d`

---

Libraries/Image/Image.web.js

When use Image.propTypes.style e.g. in github.com/zbtang/React-Native-ViewPager will cause the error, so I copy the missing code from react-native.

Fix `Uncaught TypeError: Cannot read property 'source' of undefined` 
